"""You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"
Example 3:

Input: s = "a", t = "aa"
Output: "a"
Example 4:

Input: s = "ae", t = "aea"
Output: "a"

"""

# My First way 52ms, 14.4mb
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        #first created a dictionary to str=ore values of string s
        dic = {}

        #iterate through each items of string s
        for i in s:
            #if the item is not in dictionary, put it in and give it value 1
            if i not in dic:
                dic[i] = 1
            # else increment the value of item
            else:
                dic[i] += 1
        
        #iterate through each items of string t
        for i in t:
            # if the item is in dictionary we decrement the value of item and check if the value is zero, which means no items of string s left, then we pop the item from the dictionary
            if i in dic:
                dic[i] -= 1
                if dic[i] == 0:
                    dic.pop(i)
            # else we return the item which is not present in string s
            else:
                return i